baseURL = 'https://botharetrue.com/'
languageCode = 'en-us'
title = 'Both Are True'
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "A shelter from the swarm."
  author = "Alex Dobrenko"
  defaultTheme = "auto"
  showReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  mainSections = ["posts"]

[params.profileMode]
  enabled = false

[params.assets]
  disableFingerprinting = true

[[params.socialIcons]]
  name = "email"
  url = "mailto:alex@botharetrue.com"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Essays"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "evergreen"
    name = "Evergreen"
    url = "/categories/evergreen/"
    weight = 30
  [[menu.main]]
    identifier = "reading"
    name = "Reading"
    url = "/categories/reading/"
    weight = 40
